// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlvlovbfzgvdggoudgsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdmxvdmJmemd2ZGdnb3VkZ3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzM3MDYsImV4cCI6MjA2MDg0OTcwNn0.M1EWoNQ4l1Naag47ZgduZ8R9q4ImQFB0M7JzIv8Dle0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);